services:
  yarn-install:
    build: .
    command: ["yarn", "install", "--frozen-lockfile"]
    volumes:
    - .:/home/node

  frontend:
    build: .
    working_dir: /home/node/frontend
    depends_on:
      yarn-install:
        condition: service_completed_successfully
    ports:
    - 5173:5173
    restart: unless-stopped
    volumes:
    - .:/home/node
    environment:
    - VITE_API_URL=http://backend:8000
    - MONGO_DB=mongodb://mongo/tilbot
    command: ["npm", "run", "dev-vite"]

  backend:
    build: .
    working_dir: /home/node/backend
    depends_on:
      yarn-install:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    ports:
    - 8000:8000
    restart: unless-stopped
    volumes:
    - .:/home/node
    environment:
      LISTEN_PORT: 8000
      MONGO_DB: mongodb://mongo/tilbot
    command: ["npm", "run", "start"]

  mongo:
    image: mongo
    ports:
    - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: tilbot
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 2s
      retries: 20
    volumes:
    - mongodb:/data/db

volumes:
  mongodb:
