version: "3.8"
services:
  yarn-install:
    build: .
    command: ["yarn", "install", "--frozen-lockfile"]
    volumes:
      - .:/home/node

  frontend:
    build: .
    working_dir: /home/node/frontend
    depends_on:
      yarn-install:
        condition: service_completed_successfully
    ports:
      - 5173:5173
    restart: unless-stopped
    volumes:
      - .:/home/node
    environment:
      - VITE_API_URL=http://backend:8000
      - MONGO_DB=mongodb://mongo/tilbot
    healthcheck:
      test: curl -f localhost:5173 || exit 1
      interval: 10s
      timeout: 2s
      retries: 20
    command: ["yarn", "run", "dev"]

  backend:
    build: .
    working_dir: /home/node/backend
    depends_on:
      yarn-install:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    ports:
      - 8000-8010:8000-8010
    restart: unless-stopped
    volumes:
      - .:/home/node
    environment:
      LISTEN_PORT: 8000
      MONGO_DB: mongodb://mongo/tilbot
    healthcheck:
      test: curl -f localhost:8000/api/admin_account_exists || exit 1
      interval: 10s
      timeout: 2s
      retries: 20
    command: ["yarn", "run", "start"]

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: tilbot
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 2s
      retries: 20
    volumes:
      - mongodb:/data/db
    entrypoint: sh -ec "exec docker-entrypoint.sh mongod >/dev/null 2>&1"

  tests:
    profiles:
      - testing
    build:
      context: .
      dockerfile: Dockerfile-tests
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      npm-ci:
        condition: service_completed_successfully
    environment:
      - FRONTEND_ADDRESS=frontend
    volumes:
      - .:/home/node
    command: ["sh", "-exc", "npx playwright install; npm run test-integration"]

volumes:
  mongodb:
